food/urls.py
from django.urls import path
from . import views


app_name = 'food'
'''
this is done in namespacing so u dont have to
worry about muliple apps having same name for paths
'''

urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
    path('item/', views.item, name='item'),
    path('<int:pk>/',views.FoodDetail.as_view(), name='detail'),
    # path('add/',views.create_item, name='create_item'),
    path('add/',views.CreateItem.as_view(), name='create_item'),
    #edit item
    path('update/<int:id>', views.update_item, name='update_item'),
    path('delete/<int:id>', views.delete_item, name='delete_item')
]

mysiteFood/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('food/',include('food.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_img = models.CharField(max_length=500, default="https://cdn-icons-png.flaticon.com/512/1147/1147805.png")

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pics')
    location = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.user.username

food/forms.py
from django import forms

from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_img',]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .forms import ItemForm
from .models import Item
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/details.html'
# Create your views here.
def index(request):
    item_lst = Item.objects.all()
    template = loader.get_template('food/index.html')
    context = {
        'item_lst' : item_lst
    }
    return HttpResponse(template.render(context, request))


def item(request):
    return HttpResponse('This is a food app')

def detail(request, id):
    item_gg = Item.objects.get(pk=id)
    #template = loader.get_template('food/details.html')
    context = {
        'item_gg' : item_gg
    }
    return render(request,'food/details.html', context)
    #return HttpResponse(template.render(context, request))
def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form': form})

#This is a class based view for create item
class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_img']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form': form, 'item': item})

def delete_item(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request, 'food/item-delete.html', {'item': item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
# Create your views here.


def register(request):

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Wlcome {username}, your account is created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food App</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
{% if user.is_authenticated %}
<link rel="stylesheet" href="{% static 'food/style.css' %}">
{% endif %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" style="padding: 9px" href="{% url 'food:index' %}">Food App</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="nav nav-pills ms-auto" >
              {% if user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'food:create_item' %}">Add Item </a>
              </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">LogOut</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Register</a>
              </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
              {% endif %}
          </ul>
        </div>
      </nav>
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-primary" role="alert">
              {{message}}
            </div>
          {% endfor %}
        {% endif %}
      {% if user.is_authenticated %}
          {% block body %}
          {% endblock %}
      {% else %}
          {% block login %}
          {% endblock %}
          {% block register %}
          {% endblock %}
      {% endif %}

</body>
</html>

food/templates/food/details.html
{% extends 'food/base.html'%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food App</title>
</head>
<body>
    {% block body %}
    <div>
            <div class="row" style="display: flex; justify-content: center; position: relative;" >
                <div class="col-md-7">
                    <img src="{{ object.item_img }}" class="card"/>
                </div>
                <div class="col-md-7">
                    <ol>
                        <h1>{{ object.item_name}}</h1>
                        <h2>{{ object.item_desc}}</h2>
                        <h3>${{ object.item_price}}</h3>
                     </ol>
                </div>

            </div>
            <a href="{% url 'food:delete_item' object.id %}" class="btn btn-danger"><span>Delete item</span></a>
    </div>
    {% endblock %}
</body>
</html>

food/templates/food/index.html
{% extends 'food/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

{% block body %}
<div class="row">
   <div class="card"></div>
{% for item in item_list %}
<div class="col-md-3">
    <div class="container" style="background-image: url({{item.item_img}})" >
        <div class="overlay">
          <div class = "items"></div>
          <div class = "items head">
            <p>{{ item.item_name}}</p>
            <hr>
          </div>
          <div class = "items price">
            <p class="card-text">{{ item.item_desc}}.</p>
            <p class="new">${{ item.item_price}}</p>
            <span >By:{{ item.user_name}}</span>
          </div>
          <div class="items cart">
            <i class="fa fa-shopping-cart"></i>
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success"><span>Checkout item</span></a>
            <a href="{% url 'food:update_item' item.id %}" class="btn btn-danger"><span>Edit item</span></a>
        </div>
      </div>
      </div>
  </div>


{% endfor %}
</div>
{% endblock %}
</body>
</html>

food/templates/food/item-delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <h2>Are you sure you wanna delete? {{ item.item_name }}</h2>
        <button type="submit">Confirm</button>
    </form>
</body>
</html>

food/templates/food/item-form.html
{% extends 'food/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}

        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card rounded-0">
                    <div class="card-header text-white bg-info" >
                        <h5 class="card-title">Add Item</h5>
                    </div>
                    <div class="card-body">
                        <div class="col-md-3 offset-md-4">
                        <form method="POST">
                            {% csrf_token %}
                            <!-- {{ form }} -->
                            {% for field in form %}
                                <div class="form-group">
                                    {{field.name}}
                                    <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <br>
                            <button class="btn btn-info" type="submit">Add Item</button>
                        </form>
                    </div>
                </div>
                </div>
            </div>

        </div>


    {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block login %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card rounded-0">
                    <div class="card-header text-white bg-info" >
                        <h5 class="card-title" >Login</h5>
                    </div>
                    <div class="card-body">
                        <div class="col-md-3 offset-md-3">
                        <form method="POST" class="form">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="col-md-2 offset-md-3">
                            <div class="form-group">
                                <label for="exampleInputEmail1">{{field.name}}</label>
                                {{field}}
                              </div>
                            </div>
                            {% endfor %}
                            <br>
                                <button type="submit" style="position: relative;" class="btn btn-info">Login</button>
                        </form>
                        </div>
                </div>
                </div>
            </div>

        </div>
    </div>


    {% endblock %}
</body>
</html>

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logout</title>
</head>
<body>
    <h1>You Have Been Logged Out</h1>
</body>
</html>

users/templates/users/profile.html
{% extends 'food/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
    <h1>{{ user.username }}</h1>
    <h1>{{ user.email }}</h1>
    <img src="{{ user.profile.image.url }}" height="100px"/>
    {% endblock %}
</body>
</html>

users/templates/users/register.html
{% extends 'food/base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% block register %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card rounded-0">
                    <div class="card-header text-white bg-info" >
                        <h5 class="card-title">Register</h5>
                    </div>
                    <div class="card-body">
                        <div class="col-md-3 offset-md-4">
                        <form method="POST">
                            {% csrf_token %}
                            <!-- {{ form }} -->
                            {% for field in form %}
                                <div class="form-group">
                                    {{field.name}}
                                    <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <br>
                            <button class="btn btn-info" type="submit">Sign Up</button>
                        </form>
                    </div>
                </div>
                </div>
            </div>

        </div>
    </div>
    {% endblock %}
</body>

</html>